# Generated by Django 3.2.6 on 2021-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('nome_abr', models.CharField(max_length=5, verbose_name='Apelido')),
                ('logo', models.ImageField(upload_to='', verbose_name='foto')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('num', models.IntegerField(blank=True, null=True)),
                ('placara', models.IntegerField(blank=True, null=True)),
                ('placarb', models.IntegerField(blank=True, null=True)),
                ('timea', models.ManyToManyField(related_name='time', to='livre.Time')),
                ('timeb', models.ManyToManyField(to='livre.Time')),
            ],
        ),
    ]
