# Generated by Django 3.2.6 on 2021-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0002_alter_time_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='timea',
        ),
        migrations.AddField(
            model_name='jogo',
            name='timea',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='timeb',
        ),
        migrations.AddField(
            model_name='jogo',
            name='timeb',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
