# Generated by Django 3.2.6 on 2021-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_auto_20210818_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ('rodada',)},
        ),
        migrations.AddField(
            model_name='jogo',
            name='num2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
