# Generated by Django 3.2.6 on 2021-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0005_pontuar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuar',
            name='d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuar',
            name='e',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuar',
            name='gc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuar',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuar',
            name='pg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuar',
            name='sg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pontuar',
            name='v',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pontuar',
            name='j',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pontuar',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
