# Generated by Django 3.2.6 on 2021-08-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0006_auto_20210827_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontuar',
            options={'verbose_name_plural': 'Tabelas'},
        ),
        migrations.AlterField(
            model_name='pontuar',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livre.time'),
        ),
    ]
